FROM python:3.8.2-slim-buster

RUN pip install --upgrade pip
RUN pip install numpy scipy matplotlib pandas scikit-image scikit-learn ipython jupyter seaborn \
    jax jaxlib \
    biosppy \
    xgboost